// Generated by Supabase. Regenerate with the Supabase MCP `generate_typescript_types`
// or `npx supabase gen types typescript --project-id jagcnaxdxiummknyrxhj`.
// Do not hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      access_requests: {
        Row: {
          decided_at: string | null
          decided_by: string | null
          denial_reason: string | null
          email: string
          id: string
          invite_expires_at: string | null
          invited_at: string | null
          message: string | null
          name: string | null
          requested_at: string
          status: string
          user_id: string | null
        }
        Insert: {
          decided_at?: string | null
          decided_by?: string | null
          denial_reason?: string | null
          email: string
          id?: string
          invite_expires_at?: string | null
          invited_at?: string | null
          message?: string | null
          name?: string | null
          requested_at?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          decided_at?: string | null
          decided_by?: string | null
          denial_reason?: string | null
          email?: string
          id?: string
          invite_expires_at?: string | null
          invited_at?: string | null
          message?: string | null
          name?: string | null
          requested_at?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity: string
          entity_id: string | null
          id: string
          org_id: string | null
          summary: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: string
          org_id?: string | null
          summary?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: string
          org_id?: string | null
          summary?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_emails: {
        Row: {
          added_at: string
          added_by: string | null
          email: string
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          email: string
        }
        Update: {
          added_at?: string
          added_by?: string | null
          email?: string
        }
        Relationships: []
      }
      channel_fee_rules: {
        Row: {
          active: boolean
          channel: string
          created_at: string
          fixed_fee: number
          id: string
          listing_fee: number
          org_id: string
          payment_fixed: number
          payment_percent: number
          percent_fee: number
          updated_at: string
          user_id: string
        }
        Insert: {
          active?: boolean
          channel: string
          created_at?: string
          fixed_fee?: number
          id?: string
          listing_fee?: number
          org_id: string
          payment_fixed?: number
          payment_percent?: number
          percent_fee?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          active?: boolean
          channel?: string
          created_at?: string
          fixed_fee?: number
          id?: string
          listing_fee?: number
          org_id?: string
          payment_fixed?: number
          payment_percent?: number
          percent_fee?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "channel_fee_rules_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      cultivars: {
        Row: {
          common: string | null
          genus: string | null
          id: string
          name: string
          org_id: string | null
          origin: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          common?: string | null
          genus?: string | null
          id?: string
          name: string
          org_id?: string | null
          origin?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          common?: string | null
          genus?: string | null
          id?: string
          name?: string
          org_id?: string | null
          origin?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "cultivars_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string
          email: string | null
          etsy_handle: string | null
          id: string
          name: string
          notes: string | null
          org_id: string | null
          phone: string | null
          shopify_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          etsy_handle?: string | null
          id?: string
          name: string
          notes?: string | null
          org_id?: string | null
          phone?: string | null
          shopify_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          email?: string | null
          etsy_handle?: string | null
          id?: string
          name?: string
          notes?: string | null
          org_id?: string | null
          phone?: string | null
          shopify_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      etsy_imports: {
        Row: {
          amount: number | null
          created_at: string
          csv_type: string
          etsy_key: string
          id: string
          import_batch_id: string
          occurred_on: string | null
          order_external_id: string | null
          org_id: string | null
          raw: Json
          row_type: string | null
          source_file: string
          user_id: string
        }
        Insert: {
          amount?: number | null
          created_at?: string
          csv_type: string
          etsy_key: string
          id?: string
          import_batch_id: string
          occurred_on?: string | null
          order_external_id?: string | null
          org_id?: string | null
          raw: Json
          row_type?: string | null
          source_file: string
          user_id: string
        }
        Update: {
          amount?: number | null
          created_at?: string
          csv_type?: string
          etsy_key?: string
          id?: string
          import_batch_id?: string
          occurred_on?: string | null
          order_external_id?: string | null
          org_id?: string | null
          raw?: Json
          row_type?: string | null
          source_file?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "etsy_imports_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      expenses: {
        Row: {
          amount: number
          category: string | null
          category_legacy: string | null
          created_at: string
          deductible: boolean
          description: string | null
          id: string
          notes: string | null
          occurred_on: string
          org_id: string | null
          payment_method: string | null
          receipt_url: string | null
          schedule_c_category: string | null
          source: string
          updated_at: string
          user_id: string
          vendor_id: string | null
        }
        Insert: {
          amount: number
          category?: string | null
          category_legacy?: string | null
          created_at?: string
          deductible?: boolean
          description?: string | null
          id?: string
          notes?: string | null
          occurred_on?: string
          org_id?: string | null
          payment_method?: string | null
          receipt_url?: string | null
          schedule_c_category?: string | null
          source?: string
          updated_at?: string
          user_id: string
          vendor_id?: string | null
        }
        Update: {
          amount?: number
          category?: string | null
          category_legacy?: string | null
          created_at?: string
          deductible?: boolean
          description?: string | null
          id?: string
          notes?: string | null
          occurred_on?: string
          org_id?: string | null
          payment_method?: string | null
          receipt_url?: string | null
          schedule_c_category?: string | null
          source?: string
          updated_at?: string
          user_id?: string
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "expenses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      finance_settings: {
        Row: {
          created_at: string
          default_labor_rate: number
          home_state: string
          id: string
          mileage_rate_cents: number
          org_id: string
          timezone: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          default_labor_rate?: number
          home_state?: string
          id?: string
          mileage_rate_cents?: number
          org_id: string
          timezone?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          default_labor_rate?: number
          home_state?: string
          id?: string
          mileage_rate_cents?: number
          org_id?: string
          timezone?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "finance_settings_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: true
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      integration_config: {
        Row: {
          key: string
          updated_at: string
          value: string
        }
        Insert: {
          key: string
          updated_at?: string
          value: string
        }
        Update: {
          key?: string
          updated_at?: string
          value?: string
        }
        Relationships: []
      }
      inventory: {
        Row: {
          common: string | null
          cultivar_id: string | null
          genus: string | null
          id: string
          name: string
          org_id: string | null
          stock_growout: number
          stock_juv: number
          stock_mat: number
          updated_at: string
          user_id: string
        }
        Insert: {
          common?: string | null
          cultivar_id?: string | null
          genus?: string | null
          id?: string
          name: string
          org_id?: string | null
          stock_growout?: number
          stock_juv?: number
          stock_mat?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          common?: string | null
          cultivar_id?: string | null
          genus?: string | null
          id?: string
          name?: string
          org_id?: string | null
          stock_growout?: number
          stock_juv?: number
          stock_mat?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      licenses: {
        Row: {
          created_at: string
          expires_on: string | null
          id: string
          issued_on: string | null
          issuer: string | null
          name: string
          notes: string | null
          org_id: string | null
          reference_number: string | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          expires_on?: string | null
          id?: string
          issued_on?: string | null
          issuer?: string | null
          name: string
          notes?: string | null
          org_id?: string | null
          reference_number?: string | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          expires_on?: string | null
          id?: string
          issued_on?: string | null
          issuer?: string | null
          name?: string
          notes?: string | null
          org_id?: string | null
          reference_number?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "licenses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          channel: string
          created_at: string
          cultivar_id: string | null
          external_id: string | null
          id: string
          last_synced_at: string | null
          org_id: string | null
          price: number
          status: string
          stock: number
          title: string
          updated_at: string
          url: string | null
          user_id: string
        }
        Insert: {
          channel: string
          created_at?: string
          cultivar_id?: string | null
          external_id?: string | null
          id?: string
          last_synced_at?: string | null
          org_id?: string | null
          price?: number
          status?: string
          stock?: number
          title: string
          updated_at?: string
          url?: string | null
          user_id: string
        }
        Update: {
          channel?: string
          created_at?: string
          cultivar_id?: string | null
          external_id?: string | null
          id?: string
          last_synced_at?: string | null
          org_id?: string | null
          price?: number
          status?: string
          stock?: number
          title?: string
          updated_at?: string
          url?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      mileage_log: {
        Row: {
          created_at: string
          id: string
          miles: number
          org_id: string
          purpose: string | null
          round_trip: boolean
          trip_date: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          miles?: number
          org_id: string
          purpose?: string | null
          round_trip?: boolean
          trip_date?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          miles?: number
          org_id?: string
          purpose?: string | null
          round_trip?: boolean
          trip_date?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mileage_log_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      mortality_events: {
        Row: {
          cause: string | null
          count: number
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          noted_at: string
          notes: string | null
          org_id: string | null
          user_id: string
        }
        Insert: {
          cause?: string | null
          count?: number
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          noted_at?: string
          notes?: string | null
          org_id?: string | null
          user_id: string
        }
        Update: {
          cause?: string | null
          count?: number
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          noted_at?: string
          notes?: string | null
          org_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mortality_events_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mortality_events_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mortality_events_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          name_snapshot: string
          order_id: string
          org_id: string | null
          price: number
          qty: number
          user_id: string
        }
        Insert: {
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          name_snapshot: string
          order_id: string
          org_id?: string | null
          price?: number
          qty?: number
          user_id: string
        }
        Update: {
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          name_snapshot?: string
          order_id?: string
          org_id?: string | null
          price?: number
          qty?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_items_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          channel: string
          created_at: string
          customer_id: string | null
          external_id: string | null
          id: string
          notes: string | null
          org_id: string | null
          placed_at: string
          shipping: number
          status: string
          subtotal: number
          tax: number
          total: number
          updated_at: string
          user_id: string
        }
        Insert: {
          channel: string
          created_at?: string
          customer_id?: string | null
          external_id?: string | null
          id?: string
          notes?: string | null
          org_id?: string | null
          placed_at?: string
          shipping?: number
          status?: string
          subtotal?: number
          tax?: number
          total?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          channel?: string
          created_at?: string
          customer_id?: string | null
          external_id?: string | null
          id?: string
          notes?: string | null
          org_id?: string | null
          placed_at?: string
          shipping?: number
          status?: string
          subtotal?: number
          tax?: number
          total?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      org_memberships: {
        Row: {
          created_at: string
          id: string
          org_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          org_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          org_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "org_memberships_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      plant_photos: {
        Row: {
          caption: string | null
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          org_id: string | null
          storage_path: string
          taken_at: string
          user_id: string
        }
        Insert: {
          caption?: string | null
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          org_id?: string | null
          storage_path: string
          taken_at?: string
          user_id: string
        }
        Update: {
          caption?: string | null
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          org_id?: string | null
          storage_path?: string
          taken_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plant_photos_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plant_photos_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plant_photos_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      print_jobs: {
        Row: {
          created_at: string
          id: string
          kind: string
          org_id: string | null
          payload: Json | null
          printed_at: string | null
          shipment_id: string | null
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind?: string
          org_id?: string | null
          payload?: Json | null
          printed_at?: string | null
          shipment_id?: string | null
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          org_id?: string | null
          payload?: Json | null
          printed_at?: string | null
          shipment_id?: string | null
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "print_jobs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "print_jobs_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      production_run_items: {
        Row: {
          created_at: string
          id: string
          name_snapshot: string
          org_id: string | null
          qty_used: number
          run_id: string
          supply_id: string | null
          unit_cost: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name_snapshot: string
          org_id?: string | null
          qty_used?: number
          run_id: string
          supply_id?: string | null
          unit_cost?: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name_snapshot?: string
          org_id?: string | null
          qty_used?: number
          run_id?: string
          supply_id?: string | null
          unit_cost?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_run_items_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_run_items_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "production_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_run_items_supply_id_fkey"
            columns: ["supply_id"]
            isOneToOne: false
            referencedRelation: "supplies"
            referencedColumns: ["id"]
          },
        ]
      }
      production_run_supplies: {
        Row: {
          created_at: string
          id: string
          org_id: string
          qty: number
          run_id: string
          supply_id: string | null
          unit_cost_snapshot: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          org_id: string
          qty?: number
          run_id: string
          supply_id?: string | null
          unit_cost_snapshot?: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          org_id?: string
          qty?: number
          run_id?: string
          supply_id?: string | null
          unit_cost_snapshot?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_run_supplies_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_run_supplies_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "production_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_run_supplies_supply_id_fkey"
            columns: ["supply_id"]
            isOneToOne: false
            referencedRelation: "supplies"
            referencedColumns: ["id"]
          },
        ]
      }
      production_runs: {
        Row: {
          batch_id: string | null
          created_at: string
          cultivar_id: string | null
          description: string | null
          id: string
          labor_hours: number
          labor_rate: number
          labor_type: string
          org_id: string | null
          quantity: number
          run_on: string
          unit_cost: number | null
          user_id: string
        }
        Insert: {
          batch_id?: string | null
          created_at?: string
          cultivar_id?: string | null
          description?: string | null
          id?: string
          labor_hours?: number
          labor_rate?: number
          labor_type?: string
          org_id?: string | null
          quantity?: number
          run_on?: string
          unit_cost?: number | null
          user_id: string
        }
        Update: {
          batch_id?: string | null
          created_at?: string
          cultivar_id?: string | null
          description?: string | null
          id?: string
          labor_hours?: number
          labor_rate?: number
          labor_type?: string
          org_id?: string | null
          quantity?: number
          run_on?: string
          unit_cost?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_runs_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "propagation_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_runs_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_runs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          display_name: string | null
          id: string
          is_admin: boolean
          notification_prefs: Json
          onboarded_at: string | null
          updated_at: string
        }
        Insert: {
          display_name?: string | null
          id: string
          is_admin?: boolean
          notification_prefs?: Json
          onboarded_at?: string | null
          updated_at?: string
        }
        Update: {
          display_name?: string | null
          id?: string
          is_admin?: boolean
          notification_prefs?: Json
          onboarded_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      propagation_batches: {
        Row: {
          batch_id: string
          count: number
          cultivar: string
          est_ready: string | null
          id: string
          notes: string | null
          org_id: string | null
          stage: string
          started: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          batch_id: string
          count?: number
          cultivar: string
          est_ready?: string | null
          id?: string
          notes?: string | null
          org_id?: string | null
          stage?: string
          started?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          batch_id?: string
          count?: number
          cultivar?: string
          est_ready?: string | null
          id?: string
          notes?: string | null
          org_id?: string | null
          stage?: string
          started?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "propagation_batches_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      qr_codes: {
        Row: {
          code: string
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          last_scanned_at: string | null
          org_id: string | null
          scan_count: number
          updated_at: string
          user_id: string
        }
        Insert: {
          code: string
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          last_scanned_at?: string | null
          org_id?: string | null
          scan_count?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          last_scanned_at?: string | null
          org_id?: string | null
          scan_count?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "qr_codes_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qr_codes_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qr_codes_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      recurring_expenses: {
        Row: {
          amount: number
          billing_cycle: string
          cancelled_at: string | null
          category: string | null
          created_at: string
          id: string
          name: string
          next_renewal: string | null
          notes: string | null
          org_id: string | null
          started_on: string
          status: string
          updated_at: string
          user_id: string
          vendor_id: string | null
          website: string | null
        }
        Insert: {
          amount?: number
          billing_cycle?: string
          cancelled_at?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name: string
          next_renewal?: string | null
          notes?: string | null
          org_id?: string | null
          started_on?: string
          status?: string
          updated_at?: string
          user_id: string
          vendor_id?: string | null
          website?: string | null
        }
        Update: {
          amount?: number
          billing_cycle?: string
          cancelled_at?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name?: string
          next_renewal?: string | null
          notes?: string | null
          org_id?: string | null
          started_on?: string
          status?: string
          updated_at?: string
          user_id?: string
          vendor_id?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "recurring_expenses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recurring_expenses_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      shipments: {
        Row: {
          carrier: string | null
          created_at: string
          delivered_at: string | null
          id: string
          order_id: string
          org_id: string | null
          ship_to_state: string | null
          ship_to_zip: string | null
          shipped_at: string | null
          status: string
          tracking_number: string | null
          updated_at: string
          user_id: string
          weather_hold: boolean
          weather_note: string | null
        }
        Insert: {
          carrier?: string | null
          created_at?: string
          delivered_at?: string | null
          id?: string
          order_id: string
          org_id?: string | null
          ship_to_state?: string | null
          ship_to_zip?: string | null
          shipped_at?: string | null
          status?: string
          tracking_number?: string | null
          updated_at?: string
          user_id: string
          weather_hold?: boolean
          weather_note?: string | null
        }
        Update: {
          carrier?: string | null
          created_at?: string
          delivered_at?: string | null
          id?: string
          order_id?: string
          org_id?: string | null
          ship_to_state?: string | null
          ship_to_zip?: string | null
          shipped_at?: string | null
          status?: string
          tracking_number?: string | null
          updated_at?: string
          user_id?: string
          weather_hold?: boolean
          weather_note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shipments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipments_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription_price_history: {
        Row: {
          amount: number
          created_at: string
          effective_date: string
          id: string
          org_id: string
          subscription_id: string
          user_id: string
        }
        Insert: {
          amount?: number
          created_at?: string
          effective_date?: string
          id?: string
          org_id: string
          subscription_id: string
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          effective_date?: string
          id?: string
          org_id?: string
          subscription_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscription_price_history_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscription_price_history_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          billing_cycle: string
          cancelled_at: string | null
          created_at: string
          current_period_end: string | null
          customer_id: string
          id: string
          notes: string | null
          org_id: string | null
          price: number | null
          started_at: string
          status: string
          tier: string
          updated_at: string
          user_id: string
        }
        Insert: {
          billing_cycle?: string
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          customer_id: string
          id?: string
          notes?: string | null
          org_id?: string | null
          price?: number | null
          started_at?: string
          status?: string
          tier: string
          updated_at?: string
          user_id: string
        }
        Update: {
          billing_cycle?: string
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          customer_id?: string
          id?: string
          notes?: string | null
          org_id?: string | null
          price?: number | null
          started_at?: string
          status?: string
          tier?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      supplies: {
        Row: {
          cost: number | null
          created_at: string
          id: string
          name: string
          notes: string | null
          on_hand: number
          org_id: string | null
          reorder_threshold: number | null
          unit: string | null
          updated_at: string
          user_id: string
          vendor_id: string | null
        }
        Insert: {
          cost?: number | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          on_hand?: number
          org_id?: string | null
          reorder_threshold?: number | null
          unit?: string | null
          updated_at?: string
          user_id: string
          vendor_id?: string | null
        }
        Update: {
          cost?: number | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          on_hand?: number
          org_id?: string | null
          reorder_threshold?: number | null
          unit?: string | null
          updated_at?: string
          user_id?: string
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supplies_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supplies_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      supply_purchases: {
        Row: {
          created_at: string
          expense_id: string | null
          id: string
          org_id: string
          purchase_date: string
          qty: number
          supply_id: string | null
          total_cost: number
          user_id: string
          vendor_id: string | null
        }
        Insert: {
          created_at?: string
          expense_id?: string | null
          id?: string
          org_id: string
          purchase_date?: string
          qty?: number
          supply_id?: string | null
          total_cost?: number
          user_id: string
          vendor_id?: string | null
        }
        Update: {
          created_at?: string
          expense_id?: string | null
          id?: string
          org_id?: string
          purchase_date?: string
          qty?: number
          supply_id?: string | null
          total_cost?: number
          user_id?: string
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supply_purchases_expense_id_fkey"
            columns: ["expense_id"]
            isOneToOne: false
            referencedRelation: "expenses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchases_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchases_supply_id_fkey"
            columns: ["supply_id"]
            isOneToOne: false
            referencedRelation: "supplies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchases_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assigned_to: string | null
          completed: boolean
          due: string | null
          id: string
          org_id: string | null
          title: string
          type: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          assigned_to?: string | null
          completed?: boolean
          due?: string | null
          id?: string
          org_id?: string | null
          title: string
          type?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          assigned_to?: string | null
          completed?: boolean
          due?: string | null
          id?: string
          org_id?: string | null
          title?: string
          type?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      vendors: {
        Row: {
          address: string | null
          category: string | null
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string
          id: string
          is_1099: boolean
          name: string
          notes: string | null
          org_id: string | null
          updated_at: string
          url: string | null
          user_id: string
          website: string | null
        }
        Insert: {
          address?: string | null
          category?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          is_1099?: boolean
          name: string
          notes?: string | null
          org_id?: string | null
          updated_at?: string
          url?: string | null
          user_id: string
          website?: string | null
        }
        Update: {
          address?: string | null
          category?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          is_1099?: boolean
          name?: string
          notes?: string | null
          org_id?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "vendors_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _finance_kpi_window: {
        Args: { p_end: string; p_org_id: string; p_start: string }
        Returns: Json
      }
      finance_alerts: { Args: { p_org_id: string }; Returns: Json }
      finance_cashflow: {
        Args: { p_org_id: string }
        Returns: {
          money_in: number
          money_out: number
          month: string
          net: number
        }[]
      }
      finance_kpis: {
        Args: { p_org_id: string; p_period?: string }
        Returns: Json
      }
      purge_stale_unconfirmed_users: {
        Args: { grace_days?: number }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
