// Generated by Supabase. Regenerate with the Supabase MCP `generate_typescript_types`
// or `npx supabase gen types typescript --project-id jagcnaxdxiummknyrxhj`.
// Do not hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity: string
          entity_id: string | null
          id: string
          org_id: string | null
          summary: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: string
          org_id?: string | null
          summary?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: string
          org_id?: string | null
          summary?: string | null
        }
        Relationships: []
      }
      production_runs: {
        Row: {
          batch_id: string | null
          created_at: string
          cultivar_id: string | null
          description: string | null
          id: string
          labor_hours: number
          labor_rate: number
          org_id: string | null
          quantity: number
          run_on: string
          user_id: string
        }
        Insert: {
          batch_id?: string | null
          created_at?: string
          cultivar_id?: string | null
          description?: string | null
          id?: string
          labor_hours?: number
          labor_rate?: number
          org_id?: string | null
          quantity?: number
          run_on?: string
          user_id: string
        }
        Update: {
          batch_id?: string | null
          created_at?: string
          cultivar_id?: string | null
          description?: string | null
          id?: string
          labor_hours?: number
          labor_rate?: number
          org_id?: string | null
          quantity?: number
          run_on?: string
          user_id?: string
        }
        Relationships: []
      }
      production_run_items: {
        Row: {
          created_at: string
          id: string
          name_snapshot: string
          org_id: string | null
          qty_used: number
          run_id: string
          supply_id: string | null
          unit_cost: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name_snapshot: string
          org_id?: string | null
          qty_used?: number
          run_id: string
          supply_id?: string | null
          unit_cost?: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name_snapshot?: string
          org_id?: string | null
          qty_used?: number
          run_id?: string
          supply_id?: string | null
          unit_cost?: number
          user_id?: string
        }
        Relationships: []
      }
      recurring_expenses: {
        Row: {
          amount: number
          billing_cycle: string
          cancelled_at: string | null
          category: string | null
          created_at: string
          id: string
          name: string
          next_renewal: string | null
          notes: string | null
          org_id: string | null
          started_on: string
          status: string
          updated_at: string
          user_id: string
          vendor_id: string | null
        }
        Insert: {
          amount?: number
          billing_cycle?: string
          cancelled_at?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name: string
          next_renewal?: string | null
          notes?: string | null
          org_id?: string | null
          started_on?: string
          status?: string
          updated_at?: string
          user_id: string
          vendor_id?: string | null
        }
        Update: {
          amount?: number
          billing_cycle?: string
          cancelled_at?: string | null
          category?: string | null
          created_at?: string
          id?: string
          name?: string
          next_renewal?: string | null
          notes?: string | null
          org_id?: string | null
          started_on?: string
          status?: string
          updated_at?: string
          user_id?: string
          vendor_id?: string | null
        }
        Relationships: []
      }
      organizations: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      org_memberships: {
        Row: {
          created_at: string
          id: string
          org_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          org_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          org_id?: string
          role?: string
          user_id?: string
        }
        Relationships: []
      }
      access_requests: {
        Row: {
          decided_at: string | null
          decided_by: string | null
          denial_reason: string | null
          email: string
          id: string
          invite_expires_at: string | null
          invited_at: string | null
          message: string | null
          name: string | null
          requested_at: string
          status: string
          user_id: string | null
        }
        Insert: {
          decided_at?: string | null
          decided_by?: string | null
          denial_reason?: string | null
          email: string
          id?: string
          invite_expires_at?: string | null
          invited_at?: string | null
          message?: string | null
          name?: string | null
          requested_at?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          decided_at?: string | null
          decided_by?: string | null
          denial_reason?: string | null
          email?: string
          id?: string
          invite_expires_at?: string | null
          invited_at?: string | null
          message?: string | null
          name?: string | null
          requested_at?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      admin_emails: {
        Row: {
          added_at: string
          added_by: string | null
          email: string
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          email: string
        }
        Update: {
          added_at?: string
          added_by?: string | null
          email?: string
        }
        Relationships: []
      }
      cultivars: {
        Row: {
          common: string | null
          genus: string | null
          id: string
          name: string
          origin: string | null
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          common?: string | null
          genus?: string | null
          id?: string
          name: string
          origin?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          common?: string | null
          genus?: string | null
          id?: string
          name?: string
          origin?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
      customers: {
        Row: {
          created_at: string
          email: string | null
          etsy_handle: string | null
          id: string
          name: string
          notes: string | null
          phone: string | null
          shopify_id: string | null
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          etsy_handle?: string | null
          id?: string
          name: string
          notes?: string | null
          phone?: string | null
          shopify_id?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          created_at?: string
          email?: string | null
          etsy_handle?: string | null
          id?: string
          name?: string
          notes?: string | null
          phone?: string | null
          shopify_id?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
      expenses: {
        Row: {
          amount: number
          category: string | null
          created_at: string
          description: string | null
          id: string
          occurred_on: string
          receipt_url: string | null
          updated_at: string
          user_id: string
          org_id: string | null
          vendor_id: string | null
        }
        Insert: {
          amount: number
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          occurred_on?: string
          receipt_url?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
          vendor_id?: string | null
        }
        Update: {
          amount?: number
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          occurred_on?: string
          receipt_url?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "expenses_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory: {
        Row: {
          common: string | null
          cultivar_id: string | null
          genus: string | null
          id: string
          name: string
          stock_flower: number
          stock_juv: number
          stock_mat: number
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          common?: string | null
          cultivar_id?: string | null
          genus?: string | null
          id?: string
          name: string
          stock_flower?: number
          stock_juv?: number
          stock_mat?: number
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          common?: string | null
          cultivar_id?: string | null
          genus?: string | null
          id?: string
          name?: string
          stock_flower?: number
          stock_juv?: number
          stock_mat?: number
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inventory_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
        ]
      }
      licenses: {
        Row: {
          created_at: string
          expires_on: string | null
          id: string
          issued_on: string | null
          issuer: string | null
          name: string
          notes: string | null
          reference_number: string | null
          status: string
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          created_at?: string
          expires_on?: string | null
          id?: string
          issued_on?: string | null
          issuer?: string | null
          name: string
          notes?: string | null
          reference_number?: string | null
          status?: string
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          created_at?: string
          expires_on?: string | null
          id?: string
          issued_on?: string | null
          issuer?: string | null
          name?: string
          notes?: string | null
          reference_number?: string | null
          status?: string
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
      listings: {
        Row: {
          channel: string
          created_at: string
          cultivar_id: string | null
          external_id: string | null
          id: string
          last_synced_at: string | null
          price: number
          status: string
          stock: number
          title: string
          updated_at: string
          url: string | null
          user_id: string
          org_id: string | null
        }
        Insert: {
          channel: string
          created_at?: string
          cultivar_id?: string | null
          external_id?: string | null
          id?: string
          last_synced_at?: string | null
          price?: number
          status?: string
          stock?: number
          title: string
          updated_at?: string
          url?: string | null
          user_id: string
          org_id: string | null
        }
        Update: {
          channel?: string
          created_at?: string
          cultivar_id?: string | null
          external_id?: string | null
          id?: string
          last_synced_at?: string | null
          price?: number
          status?: string
          stock?: number
          title?: string
          updated_at?: string
          url?: string | null
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listings_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
        ]
      }
      mortality_events: {
        Row: {
          cause: string | null
          count: number
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          noted_at: string
          notes: string | null
          user_id: string
          org_id: string | null
        }
        Insert: {
          cause?: string | null
          count?: number
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          noted_at?: string
          notes?: string | null
          user_id: string
          org_id: string | null
        }
        Update: {
          cause?: string | null
          count?: number
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          noted_at?: string
          notes?: string | null
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "mortality_events_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mortality_events_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          name_snapshot: string
          order_id: string
          price: number
          qty: number
          user_id: string
          org_id: string | null
        }
        Insert: {
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          name_snapshot: string
          order_id: string
          price?: number
          qty?: number
          user_id: string
          org_id: string | null
        }
        Update: {
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          name_snapshot?: string
          order_id?: string
          price?: number
          qty?: number
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          channel: string
          created_at: string
          customer_id: string | null
          external_id: string | null
          id: string
          notes: string | null
          placed_at: string
          shipping: number
          status: string
          subtotal: number
          tax: number
          total: number
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          channel: string
          created_at?: string
          customer_id?: string | null
          external_id?: string | null
          id?: string
          notes?: string | null
          placed_at?: string
          shipping?: number
          status?: string
          subtotal?: number
          tax?: number
          total?: number
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          channel?: string
          created_at?: string
          customer_id?: string | null
          external_id?: string | null
          id?: string
          notes?: string | null
          placed_at?: string
          shipping?: number
          status?: string
          subtotal?: number
          tax?: number
          total?: number
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      plant_photos: {
        Row: {
          caption: string | null
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          storage_path: string
          taken_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          caption?: string | null
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          storage_path: string
          taken_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          caption?: string | null
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          storage_path?: string
          taken_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "plant_photos_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plant_photos_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
        ]
      }
      print_jobs: {
        Row: {
          created_at: string
          id: string
          kind: string
          payload: Json | null
          printed_at: string | null
          shipment_id: string | null
          status: string
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          kind?: string
          payload?: Json | null
          printed_at?: string | null
          shipment_id?: string | null
          status?: string
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          payload?: Json | null
          printed_at?: string | null
          shipment_id?: string | null
          status?: string
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "print_jobs_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          display_name: string | null
          id: string
          is_admin: boolean
          notification_prefs: Json
          onboarded_at: string | null
          updated_at: string
        }
        Insert: {
          display_name?: string | null
          id: string
          is_admin?: boolean
          notification_prefs?: Json
          onboarded_at?: string | null
          updated_at?: string
        }
        Update: {
          display_name?: string | null
          id?: string
          is_admin?: boolean
          notification_prefs?: Json
          onboarded_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      propagation_batches: {
        Row: {
          batch_id: string
          count: number
          cultivar: string
          est_ready: string | null
          id: string
          notes: string | null
          stage: string
          started: string | null
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          batch_id: string
          count?: number
          cultivar: string
          est_ready?: string | null
          id?: string
          notes?: string | null
          stage?: string
          started?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          batch_id?: string
          count?: number
          cultivar?: string
          est_ready?: string | null
          id?: string
          notes?: string | null
          stage?: string
          started?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
      qr_codes: {
        Row: {
          code: string
          created_at: string
          cultivar_id: string | null
          id: string
          inventory_id: string | null
          last_scanned_at: string | null
          scan_count: number
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          code: string
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          last_scanned_at?: string | null
          scan_count?: number
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          code?: string
          created_at?: string
          cultivar_id?: string | null
          id?: string
          inventory_id?: string | null
          last_scanned_at?: string | null
          scan_count?: number
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "qr_codes_cultivar_id_fkey"
            columns: ["cultivar_id"]
            isOneToOne: false
            referencedRelation: "cultivars"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qr_codes_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
        ]
      }
      shipments: {
        Row: {
          carrier: string | null
          created_at: string
          delivered_at: string | null
          id: string
          order_id: string
          ship_to_state: string | null
          ship_to_zip: string | null
          shipped_at: string | null
          status: string
          tracking_number: string | null
          updated_at: string
          user_id: string
          org_id: string | null
          weather_hold: boolean
          weather_note: string | null
        }
        Insert: {
          carrier?: string | null
          created_at?: string
          delivered_at?: string | null
          id?: string
          order_id: string
          ship_to_state?: string | null
          ship_to_zip?: string | null
          shipped_at?: string | null
          status?: string
          tracking_number?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
          weather_hold?: boolean
          weather_note?: string | null
        }
        Update: {
          carrier?: string | null
          created_at?: string
          delivered_at?: string | null
          id?: string
          order_id?: string
          ship_to_state?: string | null
          ship_to_zip?: string | null
          shipped_at?: string | null
          status?: string
          tracking_number?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
          weather_hold?: boolean
          weather_note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shipments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          billing_cycle: string
          cancelled_at: string | null
          created_at: string
          current_period_end: string | null
          customer_id: string
          id: string
          notes: string | null
          price: number | null
          started_at: string
          status: string
          tier: string
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          billing_cycle?: string
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          customer_id: string
          id?: string
          notes?: string | null
          price?: number | null
          started_at?: string
          status?: string
          tier: string
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          billing_cycle?: string
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          customer_id?: string
          id?: string
          notes?: string | null
          price?: number | null
          started_at?: string
          status?: string
          tier?: string
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      supplies: {
        Row: {
          cost: number | null
          created_at: string
          id: string
          name: string
          notes: string | null
          on_hand: number
          reorder_threshold: number | null
          unit: string | null
          updated_at: string
          user_id: string
          org_id: string | null
          vendor_id: string | null
        }
        Insert: {
          cost?: number | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          on_hand?: number
          reorder_threshold?: number | null
          unit?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
          vendor_id?: string | null
        }
        Update: {
          cost?: number | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          on_hand?: number
          reorder_threshold?: number | null
          unit?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supplies_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assigned_to: string | null
          completed: boolean
          due: string | null
          id: string
          title: string
          type: string | null
          updated_at: string
          user_id: string
          org_id: string | null
        }
        Insert: {
          assigned_to?: string | null
          completed?: boolean
          due?: string | null
          id?: string
          title: string
          type?: string | null
          updated_at?: string
          user_id: string
          org_id: string | null
        }
        Update: {
          assigned_to?: string | null
          completed?: boolean
          due?: string | null
          id?: string
          title?: string
          type?: string | null
          updated_at?: string
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
      vendors: {
        Row: {
          category: string | null
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string
          id: string
          name: string
          notes: string | null
          updated_at: string
          url: string | null
          user_id: string
          org_id: string | null
        }
        Insert: {
          category?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          updated_at?: string
          url?: string | null
          user_id: string
          org_id: string | null
        }
        Update: {
          category?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
          org_id?: string | null
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]
